name: CI/CD Pipeline

on:
  push:
    branches: [masster]
  pull_request:
    branches: [master]
env:
  APP_NAME: mon-application
  NODE_VERSION: '20'

jobs:

  # ─────────────────────────────────────────
  # JOB 1 : Build
  # ─────────────────────────────────────────
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest

    steps:
      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Vérifier la version
        run: node --version
  # ─────────────────────────────────────────
  # JOB 2 : Test
  # ───────────────────────────────────
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Utiliser les variables
        run: |
          # $VAR pour les variables shell
          echo "App : $APP_NAME"
          echo "Node : $NODE_VERSION"

      - name: Variables automatiques de GitHub
        run: |
          echo "Branche : ${{ github.ref_name }}"
          echo "Auteur  : ${{ github.actor }}"
          echo "Commit  : ${{ github.sha }}"
  # ─────────────────────────────────────────
  # JOB 3 : Deploy
  # ─────────────────────────────────────────
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Déploiement
        run: echo "Déploiement en cours..."
